### ISSUE TITLE
Develop roadmap for all acts

### ISSUE THREAD

**Issue by Gensh** [Gensh/condemnation#3]
Prior to beginning writing, I had developed a preliminary Act 1 roadmap based on expectations from the original story. This roadmap still included Beatrice and Darkroot Garden, among other things. Diverging from this roadmap while also not planning for the impact of these changes has introduced a variety of issues into the story.

Revise the Act 1 roadmap to reflect the actual story progress and use it to complete a roadmap for all acts.

* [x] Asylum through Izalith
* [ ] SenFort through Archives
* [ ] Darkroot through New Londo
* [ ] Catacombs through Panopticon

**Comment by Gensh** [comment]
Act 1 roadmap in ff012ab.

**Comment by Gensh** [comment]
As of 1568f37605f25720826b6a3e171f79316d85d648, partial mapping for Act 2 and solidified overall structure. Reduced 6 acts to 4, including the total removal of the "Izalith Boss Rush."

**Comment by Gensh** [comment]
Also added blackboxing segment to be completed in parallel with the roadmapping.

**Comment by Gensh** [comment]
At this point, I'm going to make it a general requirement to update the roadmap as the story progresses. That said, this particular issue of updating the roadmap prior to continuing will be limited in scope. Rather than completing a detailed roadmap for the remainder of the story, I merely need to outline most of it in terms of broad story details and themes.

With that in mind, closing with 83e014e.
